accounts/urls.py
from django.conf import settings
from django.conf.urls import include, url
from . import views


urlpatterns = [
	url(r'^$',                         views.index,                         name='accounts index'),
#	url(r'admin$',                     views.admin_index,                   name='accounts admin index'),
#	url(r'admin_create_user$',         views.web_create_user_by_admin,      name='accounts admin create'),
	url(r'manage$',                    views.manage,                        name='accounts manage'),
	url(r'key_authenticate$',          views.web_key_authenticate,          name='accounts key_authenticate'),
#	url(r'key/(?P<key>.+)$',           views.web_key_authenticate,          name='accounts key_url_authenticate'),
	url(r'login$',                     views.login,                         name='accounts login'),
	url(r'logout$',                    views.logout,                        name='accounts logout'),
	url(r'confirm_email$',             views.confirm_email,                 name='accounts confirm_email'),
	url(r'check_username$',            views.check_username,                name='accounts check_username'),
	url(r'register$',                  views.web_register,                  name='accounts register'),
#	url(r'make_authorization_key$',    views.web_make_authorization_key,    name='accounts make_authorization_key'),
#	url(r'remove_authorization_key$',  views.web_remove_authorization_key,  name='accounts remove_authorization_key'),
	url(r'restore$',                   views.web_restore,                   name='accounts restore'),
]

admin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from . import views
from ninamori.decorators import staff_only


urlpatterns = [
	path('',                         staff_only(views.index),             name='admin index'),
	path('user_list',                staff_only(views.user_list),         name='admin user_list'),
	path('user/<str:user_id>/',      staff_only(views.manage_user),       name='admin edit_user'),
]

accounts/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _

error_messages = {
	'username': {
		'required': _('Username is required'),
	},
	'password': {
		'required': _('Password is required'),
	},
	'password_confirm': {
		'required': _('Confirmation is required'),
	},
	'email': {
		'required': _('Email address is required'),
		'invalid': _('Email address is invalid'),
	},
	'first_last_name': {
		'invalid': _('This is too long (limit is %(limit_value)s)'),
	},
	'code': {
		'requered': _('Code is requered'),
	},
}


class registration_form (forms.Form):
	username                            = forms.CharField(error_messages=error_messages['username'],          widget=forms.TextInput( attrs={'class': 'input', 'onblur': 'username_checker();', 'required': True} ), required=True)
	password                            = forms.CharField(error_messages=error_messages['password'],          required=True, widget=forms.PasswordInput( attrs={'class': 'input', 'required': True} ))
	password_confirm                    = forms.CharField(error_messages=error_messages['password_confirm'],  required=True, widget=forms.PasswordInput( attrs={'class': 'input', 'required': True} ))
	email                               = forms.EmailField(error_messages=error_messages['email'],            required=True, widget=forms.TextInput( attrs={'class': 'input', 'required': True} ))

class login_form (forms.Form):
	username                            = forms.CharField(error_messages=error_messages['username'],          required=True)
	password                            = forms.CharField(error_messages=error_messages['password'],          required=True, widget=forms.PasswordInput)
	redirect                            = forms.CharField(                                                    required=False)

class manage_form (forms.Form):
	first_name                          = forms.CharField(error_messages=error_messages['first_last_name'],   widget=forms.TextInput( attrs={'class': 'input'} ),     required=False, max_length=30)
	last_name                           = forms.CharField(error_messages=error_messages['first_last_name'],   widget=forms.TextInput( attrs={'class': 'input'} ),     required=False, max_length=30)
	password                            = forms.CharField(                                                    widget=forms.PasswordInput( attrs={'class': 'input'} ), required=False, initial=None)
	new_password                        = forms.CharField(                                                    widget=forms.PasswordInput( attrs={'class': 'input'} ), required=False, initial=None)
	new_password_confirm                = forms.CharField(                                                    widget=forms.PasswordInput( attrs={'class': 'input'} ), required=False, initial=None)

class restore_form (forms.Form):
	username                            = forms.CharField(                                                    widget=forms.TextInput( attrs={'class': 'input'} ), required=False)
	email                               = forms.EmailField(error_messages=error_messages['email'],            widget=forms.TextInput( attrs={'class': 'input'} ), required=False)
	restore                             = forms.CharField(                                                    required=False)

class restore_code_form (forms.Form):
	code                                = forms.CharField(error_messages=error_messages['code'],              widget=forms.TextInput( attrs={'class': 'input', 'required': True} ), required=True)
	restore                             = forms.CharField(                                                    required=False)

class restore_set_password_form(forms.Form):
	password                            = forms.CharField(error_messages=error_messages['password'],          required=True, widget=forms.PasswordInput( attrs={'class': 'input', 'required': True} ))
	password_confirm                    = forms.CharField(error_messages=error_messages['password_confirm'],  required=True, widget=forms.PasswordInput( attrs={'class': 'input', 'required': True} ))
	restore                             = forms.CharField(                                                    required=False)

accounts/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User, Group
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.utils.crypto import get_random_string
from django.views.decorators.http import require_http_methods

from .forms import *
from .models import *
from . import utils

import datetime
import hashlib
import logging

logger = logging.getLogger(__name__)


def index (request):
	user = request.user
	form_errors = request.session.pop('form errors') if 'form errors' in request.session else None

	initial = {
		'first_name': user.first_name,
		'last_name': user.last_name,
	} if user.is_authenticated else {}

	render_data = {
		'redirect': request.GET.get('next') or request.META.get('HTTP_REFERER') or '/',
		'key_auth': request.GET.get('key_auth'),
		'register': request.GET.get('register'),
		'code': request.GET.get('code'),
		'registration_form': registration_form,
		'manage_form': manage_form(initial=initial),
		'form_errors': form_errors,
	}
	return render(request, 'accounts/index.html', render_data)


@require_http_methods(['POST'])
def login (request):
	form = login_form(request.POST or None)
	if not form.is_valid():
		request.session['form errors'] = {'login': form.errors}
		return redirect('accounts index')

	data = form.cleaned_data
	user = authenticate(username=data['username'], password=data['password'])
	if user is not None and user.is_active:
		auth.login(request, user)
		destination = data.get('redirect') or reverse('accounts index')
		return redirect(destination)
	else:
		request.session['form errors'] = {'auth': _('Username or password mismatch')}
		return redirect('accounts index')


@require_http_methods(['POST'])
def logout (request):
	if request.user.is_authenticated:
		auth.logout(request)
		response = redirect(request.META.get('HTTP_REFERER') or '/')
		if request.COOKIES.get('mod_buttons'):
			response.set_cookie('mod_buttons', '')
		return response
	else:
		return render(request, '404.html', {'message': _('Logging out is only for those who logged in')}, status=400)


def check_username (request):
	if not request.GET.get('username'):
		return render(request, '404.html', {'message': _('You shall not pass')}, status=405)
	if User.objects.filter(username=request.GET.get('username')).exists():
		return HttpResponse('/static/img/accounts/check_username_bad.png', content_type='text/plain')
	return HttpResponse('/static/img/accounts/check_username_ok.png', content_type='text/plain')


@login_required
def confirm_email (request):
	user = request.user
	if request.method == 'POST':
		if not user.userprofile.confirmation_code_ready():
			request.session['form errors'] = {'confirmation_code': _('Confirmation code can not be remade yet')}
			return redirect('accounts index')

		utils.make_and_send_confirmation_code(user)
		return redirect('accounts index')

	code = request.GET.get('code')
	if not code:
		return render(request, '404.html', {'message': _('Get out and come back with a proper request')}, status=400)
	if utils.confirm_email(user, code):
		logger.info('[{} {}] confirmed email address [{}]'.format(user.id, user.username, user.email))
		return redirect('accounts index')
	else:
		return render(request, '403.html', {'message': _('Bad code')}, status=403)


def _register (form, perms):
	if not form.is_valid():
		return False, form
	data = form.cleaned_data
	if not data['password'] == data['password_confirm']:
		form.add_error('password_confirm', _('Passwords mismatch'))
		return False, form
	register = utils.api_register(data['username'], data['email'], data['password'], perms)
	logger.info('registration attempt [{} {}]'.format(data['username'], data['email']))
	return register, form


@require_http_methods(['POST'])
def web_register (request):
	form = registration_form(request.POST or None)
	register, form = _register(form, perms=[('accounts', 'access_accounts_management')])
	if register:
		if register['status'] == 'ok':
			user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
			auth.login(request, user)
			return redirect('accounts index')

		if register['status'] == 'error':
			if register['result'] == 'username exists':
				form.add_error('username', _('Username already exists'))
			if register['result'] == 'email exists':
				form.add_error('email', _('Email is already registered'))

	request.session['form errors'] = {'register': form.errors}
	return redirect(reverse('accounts index')+'?register=1')


def web_restore (request):
	step = request.GET.get('step')
	step = 1 if step not in ('1', '2', '3', '4') else int(step)
	if step == 4:
		return redirect('accounts index')

	if request.user.is_authenticated:
		return render(request, '404.html', {'message': _('You should not attempt to restore what you have not lost yet')}, status=400)

	restore_requested = request.session.get('accounts_restore_requested')
	if step == 1 and restore_requested:
		if (datetime.datetime.now() - datetime.datetime.strptime(restore_requested, settings.TIME_FORMAT)).total_seconds() > settings.ACCOUNT_RESTORATION_DELAY:
			request.session['accounts_restore_requested'] = None
		else:
			step = 2

	forms = {
		1: restore_form,
		2: restore_code_form,
		3: restore_set_password_form,
	}
	if request.method == 'GET':
		return render(request, 'accounts/restore.html', {
		'form': forms[step],
		'step': step,
	})

	if request.method == 'POST':
		if step == 1:
			form = restore_form(request.POST or None)
			status, form = _restore_step1(request, form)
		if step == 2:
			form = restore_code_form(request.POST or None)
			status, form = _restore_step2(request, form)
		if step == 3:
			form = restore_set_password_form(request.POST or None)
			status, form = _restore_step3(request, form)

		if not status:
			return render(request, 'accounts/restore.html', {'form': form, 'step': step})
		else:
			return redirect(reverse('accounts restore')+'?step='+str(step+1))


def _restore_step1 (request, form):
	""" Request a code byt entering either a username or an email address """
	if not form.is_valid():
		return False, form
	data = form.cleaned_data
	restore = utils.restore(data['username'], data['email'], settings.ACCOUNT_RESTORATION_DELAY)
	logger.info('restoration attempt [{} {}]'.format(data['username'], data['email']))
	if not restore['status'] == 'success':
		form.add_error('restore', _('Not enough or too much data'))
		return False, form
	request.session['accounts_restore_requested'] = datetime.datetime.now().strftime(settings.TIME_FORMAT)
	user_id = restore['user_id']
	if user_id:
		request.session['accounts_restore_user_id'] = str(user_id)
	return True, form


def _restore_step2 (request, form):
	""" Enter the code, confirming that you have access to the email account """
	if not form.is_valid():
		return False, form
	if not request.session.get('accounts_restore_requested'):
		form.add_error('restore', _('Restoration session has expired or was not started'))
		return False, form
	if not (datetime.datetime.now() - datetime.timedelta(seconds=settings.ACCOUNT_RESTORATION_DELAY)) < datetime.datetime.strptime(request.session.get('accounts_restore_requested'), settings.TIME_FORMAT):
		form.add_error('restore', _('Restoration session has expired'))
		return False, form
	data = form.cleaned_data
	if utils.veryfy_code(data['code'], request.session.get('accounts_restore_user_id'), settings.ACCOUNT_RESTORATION_DELAY):
		request.session['accounts_restore_approved'] = datetime.datetime.now().strftime(settings.TIME_FORMAT)
		return True, form
	else:
		form.add_error('restore', _('Wrong answer'))
		return False, form


def _restore_step3 (request, form):
	""" Reset password """
	if not form.is_valid():
		return False, form
	if not request.session.get('accounts_restore_approved'):
		form.add_error('restore', _('Restoration session has expired or was not started'))
		return False, form
	if not (datetime.datetime.now() - datetime.timedelta(seconds=settings.ACCOUNT_RESTORATION_DELAY)) < datetime.datetime.strptime(request.session.get('accounts_restore_approved'), settings.TIME_FORMAT):
		form.add_error('restore', _('Restoration session has expired'))
		return False, form
	data = form.cleaned_data
	if not data['password'] == data['password_confirm']:
		form.add_error('new_password_confirm', _('Passwords mismatch'))
		return False, form
	request.session['accounts_restore_approved'] = None
	request.session['accounts_restore_requested'] = None
	user = User.objects.get(id=request.session.get('accounts_restore_user_id'))
	user.set_password(data['password'])
	user.save()
	user = authenticate(username=user.username, password=data['password'])
	if user is not None and user.is_active:
		auth.login(request, user)
		if not user.userprofile.confirmation_email_valid:
			utils.confirm_email(user, None, True)
	return True, form


@login_required
@permission_required('accounts.access_accounts_management')
@require_http_methods(['POST'])
def manage (request):
	user = request.user
	form = manage_form(request.POST or None)
	valid = form.is_valid()
	request.session['form errors'] = {'manage': form.errors}
	if valid:
		data = form.cleaned_data
		password = data['password']
		passwords_match = data['new_password'] == data['new_password_confirm']

		if password:
			if user.check_password(password) and passwords_match:
				user.set_password(data['new_password'])
				data['password_updated'] = True
			elif not user.check_password(password):
				form.add_error('password', _('Invalid password'))
			elif not passwords_match:
				form.add_error('new_password_confirm', _('Passwords mismatch'))

		user.first_name = data['first_name']
		user.last_name = data['last_name']
		user.save()

templates/accounts/form.html
{% load i18n %}
{% load accounts_tags %}

{% if user.is_authenticated %}

	<form action="{% url 'accounts logout' %}" method="POST">
		<fieldset>
			{% csrf_token %}
			<h4 class="subtitle is-4">{% trans 'You seem like' %} {{ user.get_full_name|default:user.username }}</h4>
				<div class="field">
					<div class="control">
						<input class="button" type="submit" value="{% trans 'Log out' %}">
					</div>
				</div>
		</fieldset>
	</form>

{% else %}

	<form class="pure-u-xl-1-4 pure-u-lg-1-3 pure-u-md-1-2 pure-u-sm-1 pure-form pure-form-stacked" method="POST" action="{% url 'accounts login' %}">
		<fieldset>
			{% csrf_token %}

			<div class="field is-horizontal">
				<div class="field-label">
					<label class="label" for="id_username_top">{% trans 'username' %}</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control">
							<input class="input" id="id_username_top" name="username" type="text" required>
						</div>
						{% for error in form_errors.login.username %}<p class="help is-danger">{{ error }}</p>{% endfor %}
					</div>
				</div>
			</div>

			<div class="field is-horizontal">
				<div class="field-label">
					<label class="label" for="id_password_top">{% trans 'password' %}</label>
				</div>
				<div class="field-body">
					<div class="field">
						<div class="control">
							<input class="input" id="id_password_top" name="password" type="password" required>
						</div>
						{% for error in form_errors.login.password %}<p class="help is-danger">{{ error }}</p>{% endfor %}
					</div>
				</div>
			</div>

			{% if form_errors.auth %}<div class="notification is-warning">{{ form_errors.auth }}</div>{% endif %}
		</fieldset>

		<input type="hidden" name="redirect" value="{{ redirect }}">

		<hr>
		<div class="buttons is-right">
			<input class="button is-primary" type="submit" value="{% trans 'Log in' %}">
			<a class="button is-secondary" href="{% url 'accounts index' %}?register=1">{% trans 'Register' %}</a>
			<a class="button is-secondary" href="{% url 'accounts restore' %}">{% trans 'Restore' %}</a>
			<a class="button is-secondary" href="{% url 'accounts index' %}?key_auth=1">
				<img title="{% trans 'Key authentication' %}" src="/static/img/accounts/key_auth.png">
			</a>
		</div>
	</form>

{% endif %}

templates/accounts/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
	{% trans 'Account control panel' %}
	|
{% endblock %}
{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="/static/css/accounts.css">
{% endblock %}
{% block mainmenu %}
	{% include "mainmenu.html" with current_item='accounts' %}
{% endblock %}
{% block breadcrumbs %}
{% endblock %}

{% block content %}

	{% if not user.is_authenticated and key_auth %}
		<h1 class="title is-1">{% trans 'Key authentication' %}</h1>
		{% include "accounts/key_auth_form.html" %}
	{% elif not user.is_authenticated and register %}
		<h1 class="title is-1">{% trans 'New account registration' %}</h1>
		{% include "accounts/registration_form.html" %}
	{% elif not user.is_authenticated %}
		<h1 class="title is-1">{% trans 'Authentication' %}</h1>
		{% include "accounts/form.html" %}
	{% else %}
		<h1 class="title is-1">{% trans 'Members area' %}</h1>
		{% include "accounts/manage_account_email.html" %}
		{% if perms.accounts.access_accounts_management %}
			{% include "accounts/manage_account_data.html" %}
		{% endif %}
		{% include "accounts/form.html" %}
	{% endif %}
	<hr />

{% endblock %}
{% block scripts %}
	<script type="application/javascript" src="/static/js/accounts.js" async="async" defer="defer"></script>
{% endblock %}

templates/accounts/key_auth_form.html
{% load i18n %}
{% if message %}<div class="notification is-warning">{{ message }}</div>{% endif %}
<form action="{% url 'accounts key_authenticate' %}" method="POST">
	<fieldset>
		{% csrf_token %}

		<div class="field">
			<div class="control">
				<input class="input" type="password" name="key" placeholder="{% trans 'Key' %}" autofocus>
			</div>
		</div>

		<div class="field is-pulled-right">
			<div class="control">
				<input class="button is-primary" type="submit" value="{% trans 'Authenticate' %}">
			</div>
		</div>

		<input type="hidden" name="redirect" value="{{ redirect }}">
	</fieldset>
</form>

templates/accounts/manage_account_data.html
{% load i18n %}
<!-- TODO apply errorlist classes -->
<form method="POST" action="{% url 'accounts manage' %}">
	<fieldset>

		{% csrf_token %}
		<h4 class="subtitle is-4">{% trans 'Personal data' %}</h4>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_first_name">{% trans 'First name' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ manage_form.first_name }}
					</div>
					{% for error in form_errors.manage.first_name %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_last_name">{% trans 'Last name' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ manage_form.last_name }}
					</div>
					{% for error in form_errors.manage.last_name %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<h4 class="subtitle is-4">{% trans 'Password change' %}</h4>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_password">{% trans 'current password' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ manage_form.password }}
					</div>
					{% for error in form_errors.manage.password %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_new_password">{% trans 'new password' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ manage_form.new_password }}
					</div>
					{% for error in form_errors.manage.new_password %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_new_password_confirm">{% trans 'new password again' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ manage_form.new_password_confirm }}
					</div>
					{% for error in form_errors.manage.new_password_confirm %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field">
			<div class="control">
				<input class="button is-primary" type="submit" value="{% trans 'Manage' %}">
			</div>
		</div>

	</fieldset>
</form>

<hr>

templates/accounts/manage_account_email.html
{% load i18n %}
{% if message %}<div class="notification is-warning">{{ message }}</div>{% endif %}

{% if form_errors.manage.updated %}
	<div class="notification is-info" id="updated_successfully_notification">{% trans 'Updated successfully' %}</div>
	<script>
		setTimeout('document.getElementById("updated_successfully_notification").remove()', 3000);
	</script>
{% endif %}

{% if user.userprofile.confirmation_email_valid %}
	<div class="notification is-success">{% trans 'Email address confirmed' %}</div>

	{% if perms.accounts.manage_authorization_key %}
		{% if not user.userprofile.authorization_key %}
			<div class="notification is-info">{% trans 'Authorization key is not set' %}
				{% if new_key_available %}
					<form class="is-pulled-right" action="{% url 'accounts make_authorization_key' %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="make_key" value="please">
						<input class="button is-small is-info is-inverted is-outlined is-rounded" type="submit" title="{% trans 'Your key will be sent to you by email.' %}" value="{% trans 'Please make and send me a key' %}">
					</form>
				{% endif %}
			</div>
			{% if not new_key_available %}
				<div class="notification is-warning">{% trans 'New authorizarion key is not available yet' %}</div>
			{% endif %}
		{% else %}
			<div class="notification is-info">{% trans 'Authorization key is set' %}
				<a href="{% url 'accounts remove_authorization_key' %}" class="button is-small is-info is-inverted is-outlined is-rounded is-pulled-right">{% trans 'Please remove my key' %}</a>
			</div>
		{% endif %}
	{% endif %}

{% else %}
	<div class="notification is-warning">{% trans 'Email address is not confirmed yet' %}
		{% if user.userprofile.confirmation_code_ready %}
			<form class="is-pulled-right" action="{% url 'accounts confirm_email' %}" method="POST">
				{% csrf_token %}
				<input type="hidden" name="send_another_code" value="please">
				<input class="button is-small is-info is-inverted is-outlined is-rounded" type="submit" value="{% trans 'Please send me another code' %}">
			</form>
		{% else%}
			<input class="button is-small is-info is-inverted is-outlined is-rounded" disabled="" type="submit" value="{% blocktrans with time=user.userprofile.confirmation_email_sent %}Code was sent on {{time}}{%endblocktrans%}">
		{% endif %}
	</div>
	{% if form_errors.confirmation_code %}
		<div class="notification is-danger">{{ form_errors.confirmation_code }}</div>
	{% endif %}
{% endif %}

templates/accounts/registration_form.html
{% load i18n %}
{% if message %}<div class="notification is-warning">{{ message }}</div>{% endif %}
{% url 'accounts index' as accounts_index %}
<h4 class="subtitle is-4">{% blocktrans %}Have an account? You should just <a href="{{ accounts_index }}">log in</a> instead{% endblocktrans %}</h4>

<form class="register_form" method="POST" action="{% url 'accounts register' %}">
	<fieldset>
		{% csrf_token %}

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_username">{% trans 'Username' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ registration_form.username }}
						<img class="is-pulled-right" src="/static/img/accounts/check_username.png" style="cursor:pointer" title="{% trans 'check username availability' %}" id="id_username_checker" onclick="username_checker();">
					</div>
					{% for error in form_errors.register.username %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_password">{% trans 'Password' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ registration_form.password }}
					</div>
					{% for error in form_errors.register.password %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_password_confirm">{% trans 'Password again' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ registration_form.password_confirm }}
					</div>
					{% for error in form_errors.register.password_confirm %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field is-horizontal">
			<div class="field-label">
				<label class="label" for="id_email">{% trans 'Email' %}</label>
			</div>
			<div class="field-body">
				<div class="field">
					<div class="control">
						{{ registration_form.email }}
					</div>
					{% for error in form_errors.register.email %}<p class="help is-danger">{{ error }}</p>{% endfor %}
				</div>
			</div>
		</div>

		<div class="field">
			<div class="control">
				<input class="button is-primary" type="submit" value="{% trans 'Register' %}">
			</div>
		</div>

	</fieldset>
</form>

templates/accounts/restore.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
	{% trans 'Account control panel' %}
	|
	{% trans 'Restoration' %}
	|
{% endblock %}
{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="/static/css/accounts.css">
{% endblock %}
{% block mainmenu %}
	{% include "mainmenu.html" with current_item='accounts' %}
{% endblock %}
{% block breadcrumbs %}

{% endblock %}
{% block content %}

	{% if message %}<div class="notification is-warning">{{ message }}</div>{% endif %}
	<h1 class="title is-1">{% trans 'Lost account restoration' %}</h1>
	{% if step == 1 %}
		{% include "accounts/restore/step1.html" %}
	{% elif step == 2 %}
		{% include "accounts/restore/step2.html" %}
	{% elif step == 3 %}
		{% include "accounts/restore/step3.html" %}
	{% endif %}
	<hr />

{% endblock %}